import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
import NextTopLoader from "nextjs-toploader";

import { Outfit } from "next/font/google";
// import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import SmoothScrollProvider from "@/components/providers/SmoothScrollProvider";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit", // optional (for Tailwind)
});

export const metadata: Metadata = {
  title: "Yolo Heat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.variable}>
      <body>
        <NextTopLoader color="#FFDE59" height={3} showSpinner={false} />
        <SmoothScrollProvider>
        <AuthProvider>
          <AppProvider>
            {/* <Navbar /> */}
            {children}
            <Footer />
            <Toaster />
          </AppProvider>
        </AuthProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
