import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
import NextTopLoader from "nextjs-toploader";

import { Outfit } from "next/font/google";
// import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import SmoothScrollProvider from "@/components/providers/SmoothScrollProvider";
import { ChatBot } from "@/components/chatbot/chat-bot";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});

const baseMetadata: Metadata = {
  title: "Yolo Heat",
  description: "Generated by create next app",
};

interface FaviconApiResponse {
  success?: boolean;
  data?: Array<{
    image?: string;
  }>;
}

const resolveFaviconEndpoint = () => {
  if (process.env.NEXT_PUBLIC_BACKEND_URL) {
    return `${process.env.NEXT_PUBLIC_BACKEND_URL}/favicon`;
  }

  return "/api/v1/favicon";
};

const fetchFaviconUrl = async () => {
  try {
    const response = await fetch(resolveFaviconEndpoint(), {
      headers: {
        accept: "application/json",
      },
      next: {
        revalidate: 3600,
      },
    });

    if (!response.ok) {
      return null;
    }

    const result = (await response
      .json()
      .catch(() => null)) as FaviconApiResponse | null;

    return result?.success && result.data?.[0]?.image
      ? result.data[0].image
      : null;
  } catch {
    return null;
  }
};

export async function generateMetadata(): Promise<Metadata> {
  const faviconUrl = await fetchFaviconUrl();

  return {
    ...baseMetadata,
    ...(faviconUrl
      ? {
          icons: {
            icon: [{ url: faviconUrl }],
            shortcut: [{ url: faviconUrl }],
            apple: [{ url: faviconUrl }],
          },
        }
      : {}),
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={outfit.variable}>
      <body>
        <NextTopLoader color="#FFDE59" height={3} showSpinner={false} />
        <SmoothScrollProvider>
        <AuthProvider>
          <AppProvider>
            {/* <Navbar /> */}
            {children}
             <Suspense fallback={null}>
               <ChatBot />
             </Suspense>
            <Footer />
            <Toaster />
          </AppProvider>
        </AuthProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
